version: 0.2
phases:
  install:
    runtime-versions:
        dotnet: 3.0
  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore src/DotNetTwitterBot/DotNetTwitterBot.csproj
  build:
    commands:
      - echo Build started on `date`
      - dotnet publish -c release -o . src/DotNetTwitterBot/DotNetTwitterBot.csproj
      - export BUCKET=dotnet-twitter-bot-build-artifacts
      - aws cloudformation package --template-file template.yml --s3-bucket $BUCKET --output-template-file output-template.yml
      - aws lambda update-function-configuration --function-name retweet --environment "Variables={TWITTER_CONSUMER_KEY=$TWITTER_CONSUMER_KEY,TWITTER_CONSUMER_SECRET_KEY=$TWITTER_CONSUMER_SECRET_KEY,TWITTER_ACCESS_TOKEN=$TWITTER_ACCESS_TOKEN,TWITTER_ACCESS_TOKEN_SECRET=$TWITTER_ACCESS_TOKEN_SECRET}"
artifacts:
  type: zip
  files:
    - template.yml
    - output-template.yml
